language: objective-c

notifications:
  email: false

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - xctool -configuration release -project Syncany.xcodeproj -scheme Syncany build
  - mv $HOME/Library/Developer/Xcode/DerivedData/Syncany-*/Build/Products/Release/Syncany.app .
  - tar cfvz osx-notifier.app.tar.gz Syncany.app

after_success:
  - shasum -p 256 osx-notifier.app.tar.gz
