language: objective-c

notifications:
  email: false

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install jq
- chmod a+x ./.travis.sh

script:
- xctool -configuration release -project Syncany.xcodeproj -scheme Syncany build
- mv $HOME/Library/Developer/Xcode/DerivedData/Syncany-*/Build/Products/Release/Syncany.app .
- zip -r -X syncany-osx-notifier.app.zip Syncany.app

after_success:
- ./.travis.sh
- ls -al
- shasum -a 256 syncany-osx-notifier_*.app.zip

deploy:
  provider: releases
  api_key:
    secure: Xp2lwMvYLxXkGBnyJHc8LOmQJ8uq3TwbfJOFLEYTqFTkK7ee5IezSMCvzmDQPKthiTA6jufFQ/C4jK0TEM2lLWQ9Z1VgqNFLmSE0WlVCyM7gZAgDOHXKhBJbLtJIOcdu2ouGpt6WGUvFHRTJ31B7tHQ5XBbslXGzGJ/OtX+i7yQ=
  file: syncany-osx-notifier_*.app.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
