language: objective-c

env:
  global:

  # Encrypted env variable SYNCANY_API_KEY for upload
  - secure: "TBD2joSxvkDbx0JI6FZwxaOddjX1oC4QNs64XIgd7C0e12NM9D6d1tC7sjyRcv2Af4z5A6LrGlAy/9pp6vEXW2vN/o4IVh8s6+Yezu0CU+2PE9/u7IMcdVwkyZEgTZB6d/NMijOPvr8Hzor3Eh4aV1wsyoEhhfYw9/LDB0+VIOg="

notifications:
  email: false
  irc: chat.freenode.net#syncany
  
before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install jq
- brew install openssl
- brew link --force openssl
- openssl version -a
- chmod a+x ./.travis.sh
- chmod a+x ./.upload.sh

script:
- xctool -configuration release -project Syncany.xcodeproj -scheme Syncany build
- mv $HOME/Library/Developer/Xcode/DerivedData/Syncany-*/Build/Products/Release/Syncany.app .
- zip -r -X syncany-osx-notifier.app.zip Syncany.app

after_success:
- ./.travis.sh
- ./.upload.sh
