language: objective-c

env:
  global:
  # FTP credentials    
  - secure: "IYzi6korfZpdg8QiIWsgZh81J//NBZaM0ifdAkzZVDQUZkgmgmP/aCTlVZ8UATW717qtK0KDfKQjsRRsZ22O75y7VygBrLjqxYK2ZiwOqqZBBJ8a8VjQ/rA68HszqLjNxWqAzZwddRlPcLwilJrEkD5N4OiH1YuOSy+fx3QuHt4="
  - secure: "cCqmoHjM5pKBw+bjd1D28dQWvTw1yk18E+QntRocQhVdqp0d7dHmqX7zO8O23O8w6BrKGl++ZsVRRxzFunkIxqxyz6ZH9mnYC1cq6EkFFvMbp9sUx0ZIZjHa0uwufSuWJv2oZnepn4oCk2opth1rimr0JTfd9SKAyP1qUrbLugg="
  - secure: "Dex9VmSYirFRO4jMJ4MsFsAA/IrvVJfY2xaYqYg+eOty/iS+2P0a9wcnEgdVCj6vdbOfsojHDQ1pwhLgWapLG61L2Lv9WGJpEYSlgaYKVDGTILExt6VX476Ly95vuxwiAM4LePASxMaPeXyq1Msz0zgQbgTkE2PG9j3gf5N+NB0="

notifications:
  email: false

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install jq
- brew install lftp
- chmod a+x ./.travis.sh
- chmod a+x ./.upload.sh

script:
- xctool -configuration release -project Syncany.xcodeproj -scheme Syncany build
- mv $HOME/Library/Developer/Xcode/DerivedData/Syncany-*/Build/Products/Release/Syncany.app .
- zip -r -X syncany-osx-notifier.app.zip Syncany.app

after_success:
- ./.travis.sh
- ./.upload.sh
