language: objective-c

notifications:
  email: false

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - xctool -configuration release -project syncany-notifier.xcodeproj -scheme syncany-notifier build
  - mv $HOME/Library/Developer/Xcode/DerivedData/syncany-notifier-*/Build/Products/Release/syncany-notifier.app .
  - tar cfvz syncany-notifier.app.tar.gz syncany-notifier.app

after_success:
  - shasum -p 256 syncany-notifier.app.tar.gz

